# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
# 添加小目标检测层查看效果
# Parameters
nc: 45 # number of classes
depth_multiple: 0.33 # model depth multiple
width_multiple: 0.50 # layer channel multiple
# 预测框大小,预测框数量
anchors:
    3
    # - [6,6, 8,9, 12,13]
    # - [18,19, 27,28, 45,44]
# YOLOv5 v6.0 backbone
backbone:
    # [from, number, module, args]
    # args = [output, kernel, padding, stride ]
    #    卷积公式：w' = (w + 2p -k )/s + 1
    # -1 表示从上一层传进来
    # 输入 640 * 640 * 3
    [
        [-1, 1, Conv, [64, 6, 2, 2]], # 0-P1/2 CBS    # arguments:[3, 32, 6, 2, 2]
        # 320 * 320 * 32
        # [-1, 1, Focus, [64, 3]],
        [-1, 1, GhostConv, [128, 3, 1]], # 1-P2/4 Conv GhostConv
        [-1, 1, space_to_depth, [1]],
        # 160 * 160 * 64
        [-1, 3, C3Ghost, [128]], # C3Ghost C3
        [-1, 1, GhostConv, [256, 3, 1]], # 3-P3/8
        [-1, 1, space_to_depth, [1]],
        # 80 * 80 * 128
        [-1, 6, C3Ghost, [256]],
        [-1, 1, GhostConv, [512, 3, 1]], # 5-P4/16
        [-1, 1, space_to_depth, [1]], #8
        # 40 * 40 * 256
        [-1, 9, C3Ghost, [512]],
        # 20 * 20 * 512
        [-1, 1, GhostConv, [1024, 3, 1]], # 7-P5/32
        [-1, 1, space_to_depth, [1]],
        [-1, 3, C3Ghost, [1024]],
        [-1, 1, SPPF, [1024, 5]], # 9  13
    ]

# YOLOv5 v6.0 head
head: [
        [-1, 1, Conv, [512, 1, 1]],
        [-1, 1, nn.Upsample, [None, 2, 'nearest']],
        [[-1, 9], 1, Concat, [1]], # cat backbone P4
        [-1, 3, C3, [512, False]], # 13  17

        [-1, 1, Conv, [256, 1, 1]],
        [-1, 1, nn.Upsample, [None, 2, 'nearest']],
        [[-1, 6], 1, Concat, [1]], # cat backbone P3
        [-1, 3, C3, [256, False]], # 17 (P3/8-small)80*80  21

        [-1, 1, Conv, [128, 1, 1]],
        [-1, 1, nn.Upsample, [None, 2, 'nearest']],
        [[-1, 3], 1, Concat, [1]], # cat backbone P2
        [-1, 3, C3, [128, False]], # 21 (p2/4-smaller)160*160  25

        [-1, 1, Conv, [128, 3, 2]],
        [[-1, 22], 1, Concat, [1]], # cat head P4 bifpn[-1, 18, 4] [-1,22,6]
        [-1, 3, C3, [256, False]], # 24 (p3/8-samll) 80*80  28

        # [ -1, 1, Conv, [ 256, 3, 2 ] ],
        # [ [ -1, 18,9], 1, Concat, [ 1 ] ],  # cat head P4 bifpn  [-1, 14, 6] [-1,18,9]
        # [ -1, 3, C3, [ 512, False ] ],  # 27 (P4/16-medium)40*40  31

        # [ -1, 1, Conv, [ 512, 3, 2 ] ],
        # [ [ -1, 14], 1, Concat, [ 1 ] ],  # cat head P5  8->12 [-1,14,12]
        # [ -1, 3, C3, [ 1024, False ] ],  # 30 (P5/32-large)20*20  34

        [[25, 28], 1, Detect, [nc, anchors]], # Detect(P3, P4, P5)21.24.27.30  25
    ]
